### ISSUE TITLE
Tar Release added to release assets

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/secops-soar-tdx#118]
## Context

It's pretty hard to find the `tar` file meant for uploading to SOAR.

## Tasks

- [ ] add a GitHub actions step that moves/copies/links the tar file asset from the latest release whenever a tag is created (if possible)

**Comment by edthedev** [comment]
Looks like we need to know the release to get the path, as in:

```yaml
    - name: Get Current Release
        id: get_current_release
        uses: joutvhu/get-release@v1
        with:
          debug: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
